### ISSUE TITLE
Apple M1 install with homebrew

### ISSUE THREAD

**Issue by gstefanelli** [cloudwalk/ruby-3des#1]
Hey guys! Nice work there!

Just to inform that i had to set these environments on a Mac M1 install:

`export CFLAGS="-std=c99 -I /opt/homebrew/opt/openssl@1.1/include/"`
`export LDFLAGS="-lcrypto -L /opt/homebrew/opt/openssl@1.1/lib/"`
`export CPPFLAGS="-I /opt/homebrew/opt/openssl@1.1/include"`

I'm using homebrew and asdf.
Maybe you could shine more about it on docs.

Thanks!

**Comment by ananovaes** [comment]
It also works for Mac Intel Core i5
